baseURL = "https://bkdevlabs.com/"
languageCode = "en-us"
title = "BKDevLabs - Digital Web Development Agency"

[params]
  description = "A boutique digital web development agency focused on turning your vision into elegant, high-performance web solutions."
  author = "BKDevLabs"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Our Work"
    url = "/work"
    weight = 2

  [[menu.main]]
    name = "Products"
    url = "/products"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]